### ISSUE TITLE
Optimize glyphs packing

### ISSUE THREAD

**Issue by trethaller** [Yanrishatum/fontgen#7]
The current `MaxRectsPacker` seems to often produce packings where glyphs only occupy 50% of the available space, causing textures to take twice the required video memory.

![londinia_sdf](https://user-images.githubusercontent.com/1499344/72086431-30848400-3307-11ea-8633-acd19e133072.png)
![noto_sans_regular](https://user-images.githubusercontent.com/1499344/72086441-34180b00-3307-11ea-8e96-f28d314bdbe3.png)

**Comment by Yanrishatum** [comment]
Hm. I'll need to investigate other algorithms. Also most likely introduce packer configuration. so it would be possible to fine-tune currently hardcoded parts. Current unoptimal result is produced mainly due to the fact that BinPacker expects known size of the bin, which is hardcoded to 4k texture. If anything I probably will have to write my own packer algorithm that prioritizes packing everything into a rectangular area as much as possible.

**Comment by trethaller** [comment]
I'd be happy to be able to specify a maxWidth in the config file

**Comment by Yanrishatum** [comment]
v.1.5.0 introduced extensive packer configuration capabilities to fine-tune packer output, also tweaked default settings to produce more compact textures.
